CREATE TABLE PRMS_HOUSE_RENT_MASTER 
(
   BRN_TYPE          NUMBER(1),
   BASIC_MIN_AMT   NUMBER(9,2),
   BASIC_MAX_AMT   NUMBER(9,2),
   HOUSE_RENT_PCT    NUMBER(2,2),
   MIN_HR_AMT        NUMBER(9,2)          
);