-- CREATE TABLE
CREATE TABLE PRMS_EMPLOYEE
(
  EMP_ID         VARCHAR2(20) NOT NULL,
  EMP_NAME       VARCHAR2(50),
  JOINING_DESIG  VARCHAR2(45),
  JOINING_DATE   DATE,
  GENDER         VARCHAR2(1),
  BLOOD_GRP      VARCHAR2(2),
  RHFACTOR       VARCHAR2(10),
  TIN_NO         VARCHAR2(30),
  EMAIL          VARCHAR2(50),
  CONTACT_NO     VARCHAR2(12),
  DOB            DATE,
  ADDRESS        VARCHAR2(100),
  ENTD_BY        VARCHAR2(15),
  ENTD_ON        DATE,
  MOD_BY         VARCHAR2(15),
  MOD_ON         DATE,
  RELIGION       CHAR(1),
  HIGHEST_DEGREE VARCHAR2(100),
  HOME_DISTRICT  VARCHAR2(30),
  NID            VARCHAR2(20)
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE PRMS_EMPLOYEE
  ADD PRIMARY KEY (EMP_ID);
