CREATE TABLE PRMS_BONUS_TRANSACTION
  (ENTITY_NUM           NUMBER(4),
   BRANCH_CODE          VARCHAR2(6),
   EMP_ID               VARCHAR2(20),
   SAL_YEAR             NUMBER(4),
   MONTH_CODE           NUMBER(2),
   SAL_MONTH            VARCHAR2(10),
   BONUS_TYPE           VARCHAR2(5),
   BONUS_DESCRIPTION    VARCHAR2(50),
   REVENUE              NUMBER(7,2),
   RELIGION             CHAR(1),
   BONUS_ORDER_NO       VARCHAR2(30),
   BASIC_AMT            NUMBER(9,2),
   BONUS_AMOUNT         NUMBER(9,2),
   NET_BON_AMT          NUMBER(9,2),
   ENTD_BY 				VARCHAR2(10),
   ENTD_ON 				DATE
);
ALTER TABLE PRMS_BONUS_TRANSACTION ADD PRIMARY KEY(ENTITY_NUM,BRANCH_CODE,EMP_ID,SAL_YEAR,MONTH_CODE,BONUS_TYPE);
