CREATE TABLE ELMS_EMPLOYEE
(
  EMP_ID         VARCHAR2(20) NOT NULL,
  EMP_NAME       VARCHAR2(50),
  DESIG_CODE     VARCHAR2(20),
  SENIORITY_CODE NUMBER(3)
);
ALTER TABLE ELMS_EMPLOYEE ADD PRIMARY KEY (EMP_ID)