CREATE TABLE ELMS_MBRANCH
(
  BRN_CODE     VARCHAR2(5),
  BRN_NAME     VARCHAR2(50),
  BRN_ADDRESS  VARCHAR2(150),
  BRN_CATEGORY VARCHAR2(20),
  BRN_TYPE     NUMBER(3),
  ENTD_BY      VARCHAR2(15),
  ENTD_ON      DATE,
  MOD_BY       VARCHAR2(15),
  MOD_ON       DATE
);
ALTER TABLE ELMS_MBRANCH ADD PRIMARY KEY (BRN_CODE)