-- CREATE TABLE
CREATE TABLE ELMS_USER
(
  USER_ID         VARCHAR2(15) NOT NULL,
  USER_NAME       VARCHAR2(50),
  USER_PASSWORD   VARCHAR2(100),
  USER_BRANCH     VARCHAR2(5),
  USER_ROLE       CHAR(1),
  USER_DESIG_CODE VARCHAR2(5),
  ENTD_BY         VARCHAR2(15),
  ENTD_ON         DATE,
  MOD_BY          VARCHAR2(15),
  MOD_ON          DATE
);
ALTER TABLE ELMS_USER ADD PRIMARY KEY (USER_ID);