CREATE TABLE ELMS_DISBURSE
(      
   ENTITY_NUM       NUMBER(6),
   EMP_ID           VARCHAR2(20),
   LOAN_TYPE        VARCHAR2(3),
   DISB_SL          NUMBER(3),
   DISB_DATE        DATE,
   DISB_AMOUNT      NUMBER(9,2),
   INT_RATE         NUMBER(5,2),
   FIRST_REPAY_DATE DATE,
   CURR_DISB_AMT    NUMBER(9,2),
   CURR_PRIN_AMOUNT NUMBER(9,2),
   CURR_INT_AMOUNT  NUMBER(9,2),
   CURR_OS_AMOUNT   NUMBER(9,2)
);
ALTER TABLE ELMS_DISBURSE ADD PRIMARY KEY(ENTITY_NUM,EMP_ID,LOAN_TYPE,DISB_SL);
ALTER TABLE ELMS_DISBURSE DROP COLUMN CURR_PRIN_AMOUNT;
ALTER TABLE ELMS_DISBURSE DROP COLUMN CURR_INT_AMOUNT;
ALTER TABLE ELMS_DISBURSE DROP COLUMN CURR_OS_AMOUNT;
ALTER TABLE ELMS_DISBURSE ADD (ENTD_BY VARCHAR2(15),ENTD_ON DATE)
