CREATE TABLE PRMS_ALLOWANCE
  AS (SELECT * FROM TEST.PRMS_ALLOWANCE);
  
CREATE TABLE PRMS_BONUS_TRANSACTION
  AS (SELECT * FROM TEST.PRMS_BONUS_TRANSACTION);
  
CREATE TABLE PRMS_BRN_DEPARTMENT
  AS (SELECT * FROM TEST.PRMS_BRN_DEPARTMENT);
  
CREATE TABLE PRMS_DEDUC
  AS (SELECT * FROM TEST.PRMS_DEDUC);
  
CREATE TABLE PRMS_DESIGNATION
  AS (SELECT * FROM TEST.PRMS_DESIGNATION);
  
CREATE TABLE PRMS_EMPLOYEE
  AS (SELECT * FROM TEST.PRMS_EMPLOYEE);
  
CREATE TABLE PRMS_EMP_SAL
  AS (SELECT * FROM TEST.PRMS_EMP_SAL);

CREATE TABLE PRMS_EMP_SAL_HIST
  AS (SELECT * FROM TEST.PRMS_EMP_SAL_HIST);

CREATE TABLE PRMS_EMP_SAL_HIST
  AS (SELECT * FROM TEST.PRMS_EMP_SAL_HIST);

CREATE TABLE PRMS_HOUSE_RENT_MASTER
  AS (SELECT * FROM TEST.PRMS_HOUSE_RENT_MASTER);
  
CREATE TABLE PRMS_MBRANCH
  AS (SELECT * FROM TEST.PRMS_MBRANCH);
  

CREATE TABLE PRMS_TRANSACTION
  AS (SELECT * FROM TEST.PRMS_TRANSACTION);
  

CREATE TABLE PRMS_USER
  AS (SELECT * FROM TEST.PRMS_USER);