CREATE TABLE AS_LOAN_RECOVERABLE
(BRANCH_CODE VARCHAR2(10),
FINYEAR VARCHAR2(10),
GLCODE  VARCHAR2(13),
PRINCIPAL_OD_AMT NUMBER(18,2),
INTEREST_OD_AMT  NUMBER(18,2),
PRINCIPAL_FD_AMT NUMBER(18,2),
INTEREST_FD_AMT  NUMBER(18,2));

alter table as_loan_recoverable add primary key (branch_code,finYear,glcode);
