CREATE TABLE PRMS_USER(
       USER_ID VARCHAR2(15),
       USER_NAME VARCHAR2(50),
       USER_PASSWORD VARCHAR2(100),
       USER_BRANCH NUMBER(6),
       USER_ROLE CHAR(1),
       USER_DESIG_CODE VARCHAR2(5)
);
ALTER TABLE PRMS_USER ADD PRIMARY KEY (USER_ID);
ALTER TABLE PRMS_USER ADD (ENTD_BY VARCHAR2(15),ENTD_ON DATE,MOD_BY VARCHAR2(15),MOD_ON DATE);